heat_template_version: 2016-04-08
description: Deployment Description for RabbitMQ Cluster Mirror-Nodes (Script 5/5) Two Mirrors needed.

parameters:
  
  pool:
    description: pool resource
    type: string
    constraints:
    - {custom_constraint: neutron.lbaas.pool}
  
  subnet:
    description: Subnet to allocate the VIP in
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  port:
    type: number
    description: Port the load balancer should listen on
    constraints:
    - range: { min: 1, max: 65535 }

  addresses:
    type: comma_delimited_list
    description: Member Ips 

  index:
    type: number
    description: number of nodes
  
resources:
  member:
    type: OS::Neutron::LBaaS::PoolMember
    properties:
      address:  {get_param: [ addresses, {get_param: index }]}
      pool: { get_param: pool }
      protocol_port: { get_param: port }
      subnet: {get_param: subnet} 
