heat_template_version: 2015-10-15

parameters:
  network_port:
    type: string
    description: Network port for VM
  image_id:
    type: string
    description: Image used for servers
  keypair:
    type: string
    description: SSH key to connect to the servers
  flavor:
    type: string
    description: flavor used by the web servers
  rabbit_sec_port:
    type: string
    description: Network used by the server
  volume_size:
    type: number
    description: Size of the volume to be created.
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
  user_data:
    type: string
    description: user data skript
  name:
    type: string
    description: name machine

resources:
  volume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: volume_size }
      availability_zone: { get_param: availability_zone }
  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: volume }
      instance_uuid: { get_resource: instance }
      mountpoint: /dev/vdc
  instance:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      flavor: {get_param: flavor}
      image: {get_param: image_id}
      key_name: {get_param: keypair}
      networks:
      - port: {get_param: network_port}
      user_data: { get_param: user_data }
outputs:
  ip:
    value: { get_attr: [ instance, first_address ]}
  vm:
    value: { get_resource: instance }
