---
name: osb-rabbitmq

releases:
- name: osb-bosh-rabbitmq
  version: latest
- name: osb-bosh-haproxy
  version: latest
- name: prometheus
  version: latest

update:
  canaries: 1
  canary_watch_time: 15000-30000
  update_watch_time: 15000-30000
  max_in_flight: 2

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: rabbitmq
  instances: 3
  vm_type: minimal
  stemcell: default
  networks:
  - name: service
  azs:
  - z1
  persistent_disk_type: 10GB
  jobs:
  - name: rabbitmq-server
    release: osb-bosh-rabbitmq
  - name: rabbitmq_exporter
    release: prometheus
  - name: blackbox_exporter
    release: prometheus
  properties:
    rabbitmq_exporter:
      rabbitmq:
        url: https://localhost:15671
        user: ((exporter_credentials.username))
        password: ((exporter_credentials.password))
        skip_tls_verify: true
    blackbox_exporter:
      config:
        modules:
          http_2xx:
            prober: http
            http:
              basic_auth:
                username: ((exporter_credentials.username))
                password: ((exporter_credentials.password))
              tls_config:
                insecure_skip_verify: true
    rabbitmq:
      server:
        ssl:
          enabled: true
          fail_if_no_peer_cert: true
          verify: verifiy_none
          handshake_timeout: 5000
        disk_free_limit: 50000000
        fd_limit: 65536
        frame_max: 131072
        handshake_timeout: 10000
        net_ticktime: 130
        num_ssl_acceptors: 10
        num_tcp_acceptors: 10
        reverse_dns_lookups: false
        vm_memory_high_watermark: 0.4
        channel_max: 5
        plugins:
        - rabbitmq_management
        - rabbitmq_mqtt
        - rabbitmq_stomp
        - rabbitmq_auth_mechanism_ssl
        ports:
        - 5672
        - 5671
        - 1883
        - 8883
        - 61613
        - 61614
        - 15672
        - 15674
        - 15671
        users:
          - username: user
            password: test
          - username: monitor
            password: monitor
            tag: monitoring
        user_default_tag: policymaker
        admin_users:
          - username: admin
            password: admin
          - username: manager
            password: manager
            tag: monitoring
          - username: broker
            password: broker
            tag: none
        backup_users:
          - username: backup
            password: rules
        vhosts:
          - name: user_vhost
            users:
              - user
              - monitor

        #administrators:
        #  management:
        #    username: admin
        #  broker:
        #    username: admin
        cookie: "rabbit-cluster:local"
        cluster_partition_handling: autoheal
        disk_alarm_threshold: "{mem_relative,0.01}"

- name: haproxy
  instances: 1
  vm_type: minimal
  stemcell: default
  networks:
  - name: service
  azs:
  - z1
  jobs:
  - name: haproxy
    release: osb-bosh-haproxy
  - name: haproxy_exporter
    release: prometheus
    properties:
      haproxy_exporter:
        haproxy:
          scrape_uri: "unix:/var/vcap/sys/run/haproxy/stats.sock"
  properties:
    ha_proxy:
      binding_ip: 0.0.0.0
      disable_http: true
      stats_enable: true
      stats_user: admin
      stats_password: admin
      tcp:
      - name: rabbitmq
        balance: roundrobin
        port: 5672
      - name: rabbitmq-mgmt
        balance: roundrobin
        port: 15672
      - name: rabbitmq-mgmt-ssl
        balance: roundrobin
        port: 15671
        check: "check"
      - name: rabbitmq-ssl
        balance: roundrobin
        port: 5671
        check: "check"
      - name: mqtt
        balance: roundrobin
        port: 1883
        check: "check"
      - name: mqtt_ssl
        balance: roundrobin
        port: 8883
        check: "check"
      - name: stomp
        balance: roundrobin
        port: 61613
        check: "check"
      - name: stomp2
        balance: roundrobin
        port: 61614
        check: "check"

- name: smoke-tests
  lifecycle: errand
  instances: 0
  vm_type: minimal
  stemcell: default
  azs:
    - z1
  networks:
    - name: service
  jobs:
    - release: osb-bosh-rabbitmq
      name: smoke-tests
  properties:
    rabbitmq:
      smoke-tests:
        target:
          port:     5432
          username: admin
          password: admin
        backend:
          port:     6432
