---
name: osb-rabbitmq

releases:
- name: osb-bosh-rabbitmq
  version: latest
- name: osb-bosh-haproxy
  version: latest
- name: osb-bosh-monitoring
  version: latest

update:
  canaries: 1
  canary_watch_time: 15000-30000
  update_watch_time: 15000-30000
  max_in_flight: 2

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: rabbitmq
  instances: 3
  vm_type: minimal
  stemcell: default
  networks:
  - name: service
  azs:
  - z1
  persistent_disk_type: 10GB
  jobs:
  - name: rabbitmq-server
    release: osb-bosh-rabbitmq
  - name: node_exporter
    release: osb-bosh-monitoring
  - name: rabbitmq_exporter
    release: osb-bosh-monitoring
  properties:
    rabbitmq_exporter:
      user: admin
    rabbitmq-server:
      plugins:
      - rabbitmq_management
      - rabbitmq_mqtt
      - rabbitmq_stomp
      ports:
      - 5672
      - 5671
      - 1883
      - 8883
      - 61613
      - 61614
      - 15672
      - 15674
      administrators:
        management:
          username: admin
        broker:
          username: admin
      cookie: "rabbit-cluster:local"
      cluster_partition_handling: ignore
      disk_alarm_threshold: "{mem_relative,0.01}"

- name: haproxy
  instances: 1
  vm_type: minimal
  stemcell: default
  networks:
  - name: service
  azs:
  - z1
  jobs:
  - name: haproxy
    release: osb-bosh-haproxy
  - name: node_exporter
    release: osb-bosh-monitoring
  - name: haproxy_exporter
    release: osb-bosh-monitoring
  properties:
    ha_proxy:
      binding_ip: 0.0.0.0
      disable_http: true
      backend_port: 5672
      stats_enable: true
      stats_user: admin
      stats_password: admin
      tcp:
      - name: rabbitmq
        balance: roundrobin
        port: 5672

- name: smoke-tests
  lifecycle: errand
  instances: 0
  vm_type: minimal
  stemcell: default
  networks:
  - name: service
  azs:
  - z1
  jobs:
  - name: smoke-tests
    release: osb-bosh-rabbitmq
  properties:
    rabbitmq:
      smoke-tests:
        target:
          port: 5432
          username: admin
          password: admin
        backend:
          port: 6432
